# Use systemd-boot (UEFI only)
bootloader: grub
efiBootLoader: systemd-boot
efiBootLoaderTimeout: 5

# Kernel & initramfs
kernel: linux-cachyos
initramfs: initramfs-linux-cachyos.img

# EFI System Partition mount point
efiMountPoint: /boot

# GRUB paths
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"

# Preserve existing EFI entries (dual-boot safe)
keepEFI: true

# ---- MICROCODE SUPPORT ----
microcode: true

# Packages Calamares will look for inside the installed system
microcodePackages:
  - intel-ucode
  - amd-ucode

loaderEntries:
  - "timeout 5"
  - "console-mode keep"
