dontChroot: false
timeout: 999

script:
    - "-/usr/bin/pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com"
    - "-/usr/bin/pacman-key --lsign-key 3056513887B78AEB"
    - "-/usr/bin/pacman-key --recv-key 349BC7808577C592 --keyserver keyserver.ubuntu.com"
    - "-/usr/bin/pacman-key --lsign-key 349BC7808577C592"
    - "-/usr/bin/pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'"
    - "-/usr/bin/pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'"
    - "-/usr/bin/pacman -Sy --noconfirm chaotic-keyring"
    - "-/usr/bin/pacman -Syu --noconfirm"
