# Run SDDM Wayland over Hyprland compositor
# Credits to the HyDE project

[Theme]
Current=sddm-astronaut-theme
CursorTheme=BreezeDark
CursorSize=24

[General]
Numlock=on
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell

[Users]
DefaultPath=/usr/local/bin:/usr/bin:/bin
HideShells=
HideUsers=
MaximumUid=60513
MinimumUid=1000
RememberLastUser=true
RememberLastSession=true
ReuseSession=true

[Wayland]
CompositorCommand=start-hyprland -- -c /usr/share/hypr/sddm/hyprland.lua
EnableHiDPI=true

[X11]
Enable=false
