_sddm_src="/usr/share/raveos/cosmic-theme/theme-data/sddm/sddm.conf"
_sddm_dst="/etc/sddm.conf.d/raveos-theme.conf"

pre_install() {
    rm -f "$_sddm_dst"
}

pre_upgrade() {
    rm -f "$_sddm_dst"
}

post_install() {
    mkdir -p /etc/sddm.conf.d
    install -Dm644 "$_sddm_src" "$_sddm_dst"
}

post_upgrade() {
    mkdir -p /etc/sddm.conf.d
    install -Dm644 "$_sddm_src" "$_sddm_dst"
}

post_remove() {
    rm -f "$_sddm_dst"
}
