// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks_wlcontext

import (
	client "github.com/AvengeMedia/DankMaterialShell/core/pkg/go-wayland/wayland/client"
	mock "github.com/stretchr/testify/mock"
)

// MockWaylandContext is an autogenerated mock type for the WaylandContext type
type MockWaylandContext struct {
	mock.Mock
}

type MockWaylandContext_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWaylandContext) EXPECT() *MockWaylandContext_Expecter {
	return &MockWaylandContext_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockWaylandContext) Close() {
	_m.Called()
}

// MockWaylandContext_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockWaylandContext_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockWaylandContext_Expecter) Close() *MockWaylandContext_Close_Call {
	return &MockWaylandContext_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockWaylandContext_Close_Call) Run(run func()) *MockWaylandContext_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWaylandContext_Close_Call) Return() *MockWaylandContext_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWaylandContext_Close_Call) RunAndReturn(run func()) *MockWaylandContext_Close_Call {
	_c.Run(run)
	return _c
}

// Display provides a mock function with no fields
func (_m *MockWaylandContext) Display() *client.Display {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Display")
	}

	var r0 *client.Display
	if rf, ok := ret.Get(0).(func() *client.Display); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Display)
		}
	}

	return r0
}

// MockWaylandContext_Display_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Display'
type MockWaylandContext_Display_Call struct {
	*mock.Call
}

// Display is a helper method to define mock.On call
func (_e *MockWaylandContext_Expecter) Display() *MockWaylandContext_Display_Call {
	return &MockWaylandContext_Display_Call{Call: _e.mock.On("Display")}
}

func (_c *MockWaylandContext_Display_Call) Run(run func()) *MockWaylandContext_Display_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWaylandContext_Display_Call) Return(_a0 *client.Display) *MockWaylandContext_Display_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWaylandContext_Display_Call) RunAndReturn(run func() *client.Display) *MockWaylandContext_Display_Call {
	_c.Call.Return(run)
	return _c
}

// FatalError provides a mock function with no fields
func (_m *MockWaylandContext) FatalError() <-chan error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FatalError")
	}

	var r0 <-chan error
	if rf, ok := ret.Get(0).(func() <-chan error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan error)
		}
	}

	return r0
}

// MockWaylandContext_FatalError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FatalError'
type MockWaylandContext_FatalError_Call struct {
	*mock.Call
}

// FatalError is a helper method to define mock.On call
func (_e *MockWaylandContext_Expecter) FatalError() *MockWaylandContext_FatalError_Call {
	return &MockWaylandContext_FatalError_Call{Call: _e.mock.On("FatalError")}
}

func (_c *MockWaylandContext_FatalError_Call) Run(run func()) *MockWaylandContext_FatalError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWaylandContext_FatalError_Call) Return(_a0 <-chan error) *MockWaylandContext_FatalError_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWaylandContext_FatalError_Call) RunAndReturn(run func() <-chan error) *MockWaylandContext_FatalError_Call {
	_c.Call.Return(run)
	return _c
}

// Post provides a mock function with given fields: fn
func (_m *MockWaylandContext) Post(fn func()) {
	_m.Called(fn)
}

// MockWaylandContext_Post_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Post'
type MockWaylandContext_Post_Call struct {
	*mock.Call
}

// Post is a helper method to define mock.On call
//   - fn func()
func (_e *MockWaylandContext_Expecter) Post(fn interface{}) *MockWaylandContext_Post_Call {
	return &MockWaylandContext_Post_Call{Call: _e.mock.On("Post", fn)}
}

func (_c *MockWaylandContext_Post_Call) Run(run func(fn func())) *MockWaylandContext_Post_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func()))
	})
	return _c
}

func (_c *MockWaylandContext_Post_Call) Return() *MockWaylandContext_Post_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWaylandContext_Post_Call) RunAndReturn(run func(func())) *MockWaylandContext_Post_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function with no fields
func (_m *MockWaylandContext) Start() {
	_m.Called()
}

// MockWaylandContext_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockWaylandContext_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockWaylandContext_Expecter) Start() *MockWaylandContext_Start_Call {
	return &MockWaylandContext_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockWaylandContext_Start_Call) Run(run func()) *MockWaylandContext_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWaylandContext_Start_Call) Return() *MockWaylandContext_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWaylandContext_Start_Call) RunAndReturn(run func()) *MockWaylandContext_Start_Call {
	_c.Run(run)
	return _c
}

// NewMockWaylandContext creates a new instance of MockWaylandContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWaylandContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWaylandContext {
	mock := &MockWaylandContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
