[Theme]
Current=sddm-rave-theme
CursorTheme=BreezeDark
CursorSize=24

[General]
Numlock=on
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Users]
DefaultPath=/usr/local/bin:/usr/bin:/bin
HideShells=
HideUsers=
MaximumUid=60513
MinimumUid=1000
RememberLastUser=true
RememberLastSession=true
ReuseSession=true
