dontChroot: true
timeout: 3600

script:
  - command: "/usr/bin/pacman-key --init && /usr/bin/pacman-key --populate"
    name: "Initializing package signing keys..."
  - command: "pacstrap ${ROOT} base base-devel raveos-keyring linux-cachyos linux-cachyos-headers linux-firmware networkmanager iwd broadcom-wl-dkms wireless-regdb nano vim grub rsync efibootmgr bash-completion dkms lsb-release mkinitcpio-openswap"
    name: "Bootstrapping Arch Linux (Netinstall)..."
