dontChroot: false
timeout: 3600

script:
  - command: "systemctl enable NetworkManager.service || true"
  - command: "systemctl enable iwd.service || true"
  - command: "systemctl enable bluetooth.service || true"
  - command: "systemctl enable sddm.service || true"
  - command: "systemctl enable gdm.service || true"
  - command: "systemctl enable cosmic-greeter.service || true"
  - command: "mkdir -p /etc/NetworkManager/conf.d && printf '[device]\nwifi.backend=iwd\n' > /etc/NetworkManager/conf.d/wifi_backend.conf || true"
  - command: "mkdir -p /etc/iwd && printf '[General]\nEnableNetworkConfiguration=false\n' > /etc/iwd/main.conf || true"
  - command: "ln -sf /dev/null /etc/systemd/system/wpa_supplicant.service || true"
  - command: "pacman -S --noconfirm raveos-app-installer || true"
  - command: "pacman -Sdd --noconfirm yaru-gtk-theme || true"
  - command: "rm -f /usr/share/wayland-sessions/gnome-classic*.desktop /usr/share/xsessions/gnome-classic*.desktop || true"
  - command: "sed -i 's/^#IgnorePkg/IgnorePkg/' /etc/pacman.conf || true"
  - command: "systemctl disable sleep.target suspend.target hibernate.target hybrid-sleep.target geoclue.service || true"
  - command: "systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target geoclue.service || true"
  - command: "systemctl enable reflector-once.service || true"
  - command: "systemctl enable ananicy-cpp.service || true"
    name: "Enabling services and Display Managers"
