cursor #e0e4db
cursor_text_color #c2c9bd

foreground            #e0e4db
background            #10140f
selection_foreground  #000000
selection_background  #81c995
url_color             #4caf50

color0   #10140f
color1   #c96a4c
color2   #4daf4c
color3   #dacb52
color4   #35a639
color5   #005103
color6   #4caf50
color7   #abb7ab
color8   #717b71
color9   #eca088
color10  #80d27e
color11  #fff39a
color12  #63c067
color13  #89e38d
color14  #b6f4b9
color15  #f6fdf6
