// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks_wlclient

import (
	client "github.com/AvengeMedia/DankMaterialShell/core/pkg/go-wayland/wayland/client"
	mock "github.com/stretchr/testify/mock"
)

// MockWaylandDisplay is an autogenerated mock type for the WaylandDisplay type
type MockWaylandDisplay struct {
	mock.Mock
}

type MockWaylandDisplay_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWaylandDisplay) EXPECT() *MockWaylandDisplay_Expecter {
	return &MockWaylandDisplay_Expecter{mock: &_m.Mock}
}

// Context provides a mock function with no fields
func (_m *MockWaylandDisplay) Context() *client.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 *client.Context
	if rf, ok := ret.Get(0).(func() *client.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Context)
		}
	}

	return r0
}

// MockWaylandDisplay_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockWaylandDisplay_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockWaylandDisplay_Expecter) Context() *MockWaylandDisplay_Context_Call {
	return &MockWaylandDisplay_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockWaylandDisplay_Context_Call) Run(run func()) *MockWaylandDisplay_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWaylandDisplay_Context_Call) Return(_a0 *client.Context) *MockWaylandDisplay_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWaylandDisplay_Context_Call) RunAndReturn(run func() *client.Context) *MockWaylandDisplay_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Destroy provides a mock function with no fields
func (_m *MockWaylandDisplay) Destroy() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Destroy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWaylandDisplay_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type MockWaylandDisplay_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
func (_e *MockWaylandDisplay_Expecter) Destroy() *MockWaylandDisplay_Destroy_Call {
	return &MockWaylandDisplay_Destroy_Call{Call: _e.mock.On("Destroy")}
}

func (_c *MockWaylandDisplay_Destroy_Call) Run(run func()) *MockWaylandDisplay_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWaylandDisplay_Destroy_Call) Return(_a0 error) *MockWaylandDisplay_Destroy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWaylandDisplay_Destroy_Call) RunAndReturn(run func() error) *MockWaylandDisplay_Destroy_Call {
	_c.Call.Return(run)
	return _c
}

// GetRegistry provides a mock function with no fields
func (_m *MockWaylandDisplay) GetRegistry() (*client.Registry, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRegistry")
	}

	var r0 *client.Registry
	var r1 error
	if rf, ok := ret.Get(0).(func() (*client.Registry, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *client.Registry); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Registry)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWaylandDisplay_GetRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRegistry'
type MockWaylandDisplay_GetRegistry_Call struct {
	*mock.Call
}

// GetRegistry is a helper method to define mock.On call
func (_e *MockWaylandDisplay_Expecter) GetRegistry() *MockWaylandDisplay_GetRegistry_Call {
	return &MockWaylandDisplay_GetRegistry_Call{Call: _e.mock.On("GetRegistry")}
}

func (_c *MockWaylandDisplay_GetRegistry_Call) Run(run func()) *MockWaylandDisplay_GetRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWaylandDisplay_GetRegistry_Call) Return(_a0 *client.Registry, _a1 error) *MockWaylandDisplay_GetRegistry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWaylandDisplay_GetRegistry_Call) RunAndReturn(run func() (*client.Registry, error)) *MockWaylandDisplay_GetRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// Roundtrip provides a mock function with no fields
func (_m *MockWaylandDisplay) Roundtrip() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Roundtrip")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWaylandDisplay_Roundtrip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Roundtrip'
type MockWaylandDisplay_Roundtrip_Call struct {
	*mock.Call
}

// Roundtrip is a helper method to define mock.On call
func (_e *MockWaylandDisplay_Expecter) Roundtrip() *MockWaylandDisplay_Roundtrip_Call {
	return &MockWaylandDisplay_Roundtrip_Call{Call: _e.mock.On("Roundtrip")}
}

func (_c *MockWaylandDisplay_Roundtrip_Call) Run(run func()) *MockWaylandDisplay_Roundtrip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWaylandDisplay_Roundtrip_Call) Return(_a0 error) *MockWaylandDisplay_Roundtrip_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWaylandDisplay_Roundtrip_Call) RunAndReturn(run func() error) *MockWaylandDisplay_Roundtrip_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWaylandDisplay creates a new instance of MockWaylandDisplay. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWaylandDisplay(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWaylandDisplay {
	mock := &MockWaylandDisplay{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
